### ISSUE TITLE
SafetyTutorial import error

### ISSUE THREAD

**Issue by jmvillalba** [osate/examples#12]
Hi. I'm stating with AADL and OSATE. When I import SafetTutorial example I get errors and warnings
Description	Resource	Path	Location	Type
Referenced error propagation flightSurfaceControl must be an in propagation	FlightSystem.aadl	/SafetyTutorial/packages	line: 8 /SafetyTutorial/packages/FlightSystem.aadl	Xtext Check (fast)
Referenced error propagation flightSurfaceControl must be an in propagation	FlightSystem.aadl	/SafetyTutorial/packages	line: 9 /SafetyTutorial/packages/FlightSystem.aadl	Xtext Check (fast)
Referenced error propagation location must be an in propagation	GPSSystem.aadl	/SafetyTutorial/packages	line: 6 /SafetyTutorial/packages/GPSSystem.aadl	Xtext Check (fast)
Referenced error propagation location must be an in propagation	GPSSystem.aadl	/SafetyTutorial/packages	line: 7 /SafetyTutorial/packages/GPSSystem.aadl	Xtext Check (fast)
Referenced error propagation location must be an in propagation	GPSSystem.aadl	/SafetyTutorial/packages	line: 7 /SafetyTutorial/packages/GPSSystem.aadl	Xtext Check (fast)
Referenced error propagation location must be an in propagation	GPSSystem.aadl	/SafetyTutorial/packages	line: 9 /SafetyTutorial/packages/GPSSystem.aadl	Xtext Check (fast)
Referenced error propagation outLocation must be an in propagation	GPSSystem.aadl	/SafetyTutorial/packages	line: 6 /SafetyTutorial/packages/GPSSystem.aadl	Xtext Check (fast)

How can i fix it? Thanks!

My osate version is: Version: 2.7.0.vfinal -- Build id: 2020-02-04

**Comment by lwrage** [comment]
This is a [bug](https://github.com/osate/osate2/issues/2209) in OSATE 2.7.0 which is fixed in OSATE 2.7.1.
