### ISSUE TITLE
Simple.aadl

### ISSUE THREAD

**Issue by flambye94** [osate/examples#13]
I use OSATE2 2.6.1.vfinal.

When testing the [examples simple.aadl](https://github.com/osate/examples/blob/master/core-examples/hardware-flows/simple.aadl).
I get issues that say: 
_"mybus..."_ `must be a port, parameter, data access, feature group, or abstract feature.`

I have three questions:
- Is this example "deprecated"?
- Is it my osate2 version that does not work properly?
- Could you correct this example?

Best regards

**Comment by lwrage** [comment]
This example is not valid because flows through bus access connections are not supported in AADL 2, so the example is deprecated.
