### ISSUE TITLE
syntaxical errors in the PRISM generated models

### ISSUE THREAD

**Issue by sma350** [osate/examples#3]
Hi,

first of all thank you for your help in my previous issue. I have a new problem with the PRISM models generated in OSATE. 

When I used the model checker PRISM (version 4.1.beta 2-linux 64) to analyze the models generated in OSATE I found syntactic errors in the generated model ".pm" in some examples. I want to know what version of PRISM I have to use to analyze these PRISM models.

For information, I asked for help in the PRISM forum about the errors in the model example "embedded-control," here is the link of the problem and the solution that was given to me:

https://groups.google.com/forum/?fromgroups #! topic/prismmodelchecker/UmBLG9ur1n0

Best regards,

Smail.

**Comment by geniusqu** [comment]
> Hi,
> 
> first of all thank you for your help in my previous issue. I have a new problem with the PRISM models generated in OSATE.
> 
> When I used the model checker PRISM (version 4.1.beta 2-linux 64) to analyze the models generated in OSATE I found syntactic errors in the generated model ".pm" in some examples. I want to know what version of PRISM I have to use to analyze these PRISM models.
> 
> For information, I asked for help in the PRISM forum about the errors in the model example "embedded-control," here is the link of the problem and the solution that was given to me:
> 
> https://groups.google.com/forum/?fromgroups #! topic/prismmodelchecker/UmBLG9ur1n0
> 
> Best regards,
> 
> Smail.
Can you tell me how to generate PRISM models using osate
