### ISSUE TITLE
Plug-in of PRISM for OSATE

### ISSUE THREAD

**Issue by ksk261188** [osate/examples#5]
Hi, 

Can anyone suggest the suitable procedure in developing the plugin of PRISM for OSATE? We are working in Aerospace domain and have lot of AADL Aerospace architecture models that needs to be verified using PRISM.

**Comment by ZenCCoding** [comment]
Sorry , I don't know it. But can U post the video of tutorial online?  I'm learning AADL but something really confused me like architecture design, how to make my model completely. Yes, I am reading Feiler's book "Model-based engineering with AADL' but it didn't support some backgroud about AADL. If you can give me some suggestions about how to learn and study it I am really happy and do my best to extend it:)

**Comment by lwrage** [comment]
This is for bug reports. Please post questions on the mailing list.
