### ISSUE TITLE
Multiple errors in project after import

### ISSUE THREAD

**Issue by sisso19** [osate/examples#6]
Hello

For the last couple of days I have been trying to get into AADL and is not going as well as I hoped.
I am trying to use your examples to get started but I am unable to get it up and running.

I watched a video on one of your examples on [speed regulation](http://www.sei.cmu.edu/webinars/view_webinar.cfm?webinarid=424907) and wanted to try that out first.

I am unable to get anything out of it because of the multiple errors I am getting in the project [errors.txt](https://github.com/osate/examples/files/447554/errors.txt) (Please note that this is a html file, please change the extension from txt to html). I have tested a few others and the seem to always get errors.

I followed the instructions online to [install osate](http://osate.github.io/download-and-install.html#installation) and currently have version 2.2.1.vupdate01 
My java jdk is 1.8.0_101

Here is a example of the environment I am working with
![image](https://cloud.githubusercontent.com/assets/6954895/18134265/d2bf7df0-6f6b-11e6-84cb-82f10d84c842.png)

I tried also cloning both osate2-core and osate2-plugins and copied the content to my plug-in folder in the osate2 folder without any changes.

Am i missing some configuration or package to be able to work with this repository?

**Comment by backesj** [comment]
Hello,

I suspect your "speed-regulation" project is not actually an AADL Project?
Did you start a new AADL project when you created it? The icons in your
AADL Navigator should look different.

- John

**Comment by sisso19** [comment]
Hello john and thank you for your fast answer.

I imported it from the file -> import -> existing project

Please tell me how you would recommend me to import the project

**Comment by sisso19** [comment]
@backesj You were right.
The projects can not be imported straight.
I had to create a AADL project and the import the .aadl files to the project.

I dont have an errors now so I will be able to fiddle around with this.

Thank you!

**Comment by backesj** [comment]
That usually works for me... I'm not sure how yours got messed up.  For
some reason your OSATE did not think that it was an AADL project.  You can
always create a new AADL project and then copy/paste the files into the
project.

- John
