### ISSUE TITLE
Redundant GPS in Speed regulation not redundant in Fault Tree

### ISSUE THREAD

**Issue by Sigurthorb** [osate/examples#7]
I am looking into the speed regulation example and generating a Fault Tree
My understanding of redundant components in a fault tree should have an and operator above both.

Is there a way to represent redundant components in AADL so that the fault tree exported is correct?

![image](https://cloud.githubusercontent.com/assets/6954895/19809880/40661f3e-9cf9-11e6-8e16-b45ba94cd27b.png)

**Comment by reteprelief** [comment]
Check out https://github.com/osate/examples/tree/master/SafetyTutorial and https://github.com/cmu-sei/emfta/blob/develop/doc/white-paper.md for fault tree generation from a GPS example with redundant sensors.
Looks like we have to update the speed regulation example.

**Comment by sisso19** [comment]
Thank you for the links @reteprelief 
I will take a look at this
