### ISSUE TITLE
various errors reported against Embedded Control example

### ISSUE THREAD

**Issue by Bazmundi** [osate/examples#9]
I have a new download of osate2 2.3.4 on debian 9.  The first example I pulled into and AADL project was the embedded controller (as I wanted to play with the prism export).  Embedded-control and embedded-control-advance files report errors against s1..s3 and a1..a2, at the ends of the files where the wing values are set.  Errors of the form below (subset used to avoid clutter):

Description	Resource	Path	Location	Type
Couldn't resolve reference to 's1'.	embedded-control-advanced.aadl	/embedded-control/aadl-model	line: 19 /embedded-control/aadl-model/embedded-control-advanced.aadl	Xtext Check (fast)

Description	Resource	Path	Location	Type
Couldn't resolve reference to 'Failed'.	embedded-control.aadl	/embedded-control/aadl-model	line: 19 /embedded-control/aadl-model/embedded-control.aadl	Xtext Check (fast)

What would I need do to fix this?  Is there lib or other file or is this a problem with the example?

Cheers,
A

**Comment by geniusqu** [comment]
I have the same problem as you. Have you solved this problem?
Thank you

**Comment by reteprelief** [comment]
Fixed. Had to change syntax for applies to path to subcomponents due to ambiguities.
